name: Simple Workflow
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: gemfile
          filter_mode: nofilter
          level: info
          reporter: github-pr-review
          fail_on_error: false
      - name: Run a script
        run: echo "Hello, World!"
